export interface FaqItem {
  question: string;
  answer: string;
}

export const faqData: FaqItem[] = [
  {
    question: 'What is bond yield?',
    answer:
      'Bond yield is the return an investor realizes on a bond investment. It represents the income generated by a bond relative to its price. There are several types of yield, including current yield (annual coupon payment divided by the current market price) and yield to maturity (the total return anticipated if the bond is held until it matures). Bond yield is a key metric investors use to compare the attractiveness of different fixed-income securities.',
  },
  {
    question: 'What is the difference between coupon rate and yield?',
    answer:
      'The coupon rate is the fixed annual interest rate set when the bond is issued, expressed as a percentage of the face (par) value. It does not change over the life of the bond. Yield, on the other hand, reflects the actual return an investor earns based on the price they paid for the bond. If a bond is purchased at a discount (below par), the yield will be higher than the coupon rate. If purchased at a premium (above par), the yield will be lower than the coupon rate. The coupon rate is contractual; the yield is market-driven.',
  },
  {
    question: 'How is Current Yield calculated?',
    answer:
      "Current Yield is calculated by dividing the bond's annual coupon payment by its current market price and expressing the result as a percentage. The formula is: Current Yield = (Annual Coupon Payment / Current Market Price) x 100. For example, a bond with a $1,000 face value, a 5% coupon rate, and a market price of $950 would have a current yield of ($50 / $950) x 100 = 5.26%. Current yield only considers coupon income and does not account for capital gains or losses at maturity.",
  },
  {
    question: 'How is Yield to Maturity (YTM) calculated?',
    answer:
      'Yield to Maturity (YTM) is the total return anticipated on a bond if it is held until maturity. It accounts for all coupon payments, the difference between the purchase price and face value, and the time value of money. The YTM calculation solves for the discount rate that makes the present value of all future cash flows (coupon payments + face value at maturity) equal to the current market price. Because this involves solving a polynomial equation, YTM is typically computed using iterative numerical methods such as the Newton-Raphson method or bisection method.',
  },
  {
    question: 'What is the difference between Current Yield and YTM?',
    answer:
      "Current Yield only measures the income component of a bond's return -- it divides the annual coupon by the current price. It ignores any capital gain or loss that occurs when the bond matures at par value. YTM provides a more comprehensive measure by incorporating both the coupon income and any capital gain or loss realized at maturity, as well as the reinvestment of coupon payments. For a bond trading at par, current yield and YTM are equal. For bonds trading at a premium or discount, YTM gives a more accurate picture of total expected return.",
  },
  {
    question: 'What does it mean when a bond trades at a premium or discount?',
    answer:
      "A bond trades at a premium when its market price is above its face (par) value. This happens when the bond's coupon rate is higher than prevailing market interest rates, making it more attractive to investors. Conversely, a bond trades at a discount when its market price is below face value, typically because its coupon rate is lower than current market rates. A bond trading at par means its market price equals its face value, and its coupon rate is in line with market rates. Premium bonds have yields below their coupon rate, while discount bonds have yields above their coupon rate.",
  },
  {
    question: 'Does bond yield equal yield to maturity?',
    answer:
      'Not necessarily. "Bond yield" is a general term that can refer to different yield measures, including current yield, yield to maturity (YTM), yield to call (YTC), or yield to worst (YTW). YTM is the most commonly referenced yield measure and is often what people mean when they say "bond yield," but the two terms are not strictly synonymous. YTM specifically refers to the annualized total return expected if the bond is held to maturity, while bond yield could refer to any of the yield metrics depending on context.',
  },
  {
    question: 'Can bond yield be negative?',
    answer:
      "Yes, bond yields can be negative, though it is uncommon. Negative yields occur when investors are willing to pay more for a bond than they will receive in total coupon payments plus the return of principal. This has been observed in government bonds of countries with very low or negative interest rate policies, such as Japan, Germany, and Switzerland. Investors may accept negative yields during periods of economic uncertainty as a safe haven for capital preservation, or when they expect deflation that would increase the real value of the bond's fixed payments.",
  },
  {
    question: 'What is a yield curve?',
    answer:
      'A yield curve is a graphical representation that plots the yields (interest rates) of bonds with the same credit quality but different maturity dates. The most commonly referenced yield curve shows U.S. Treasury bond yields across maturities from 1 month to 30 years. A normal yield curve slopes upward, indicating higher yields for longer-term bonds to compensate for the increased risk of holding bonds over longer periods. An inverted yield curve, where short-term yields exceed long-term yields, is often considered a predictor of economic recession. A flat yield curve suggests uncertainty about future economic conditions.',
  },
  {
    question: 'What causes bond yields to rise or fall?',
    answer:
      'Bond yields are influenced by several factors. Central bank interest rate decisions have the most direct impact -- when central banks raise rates, bond yields tend to rise, and vice versa. Inflation expectations also play a major role: higher expected inflation leads to higher yields as investors demand compensation for the erosion of purchasing power. Economic growth prospects, government fiscal policy, supply and demand for bonds, credit risk, and global market conditions all affect yields. During economic uncertainty, investors often flock to safe-haven bonds (like U.S. Treasuries), driving up prices and pushing yields down. Conversely, a strong economy can lead to higher yields as investors shift toward riskier assets.',
  },
];
